CFLAGS = -std=gnu11 -Wall -Wextra -fopenmp
.PHONY: all
all: ex2a ex2a_par ex2b ex2b_par ex2c ex2c_par

.PHONY: clean
clean:
	$(RM) ex2a ex2a_par ex2b ex2b_par ex2c ex2c_par

Task1: ex2a.c ex2a_par.c ex2b ex2b_par ex2c ex2c_par


