CFLAGS = -std=gnu11 -Wall -Wextra -lm -fopenmp -g -O3

.PHONY: all
all: eight_queens eight_queens_par

.PHONY: clean
clean:
	$(RM) eight_queens eight_queens_par

ex3: eight_queens.c eight_queens_par.c
